language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/coverage

script:
  - vendor/bin/phpunit -c module/User/tests/phpunit.xml --coverage-clover build/coverage/coverage.xml

after_script:
   # Check the code-coverage
   # - vendor/bin/coveralls -v

matrix:
  fast_finish: true
