<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Exam\Module'                        => __DIR__ . '/Module.php',
    'Exam\Controller\TestController' => __DIR__ . '/src/Exam/Controller/TestController.php',
    'ExamTest\Framework\TestCase'        => __DIR__ . '/tests/Exam/Framework/TestCase.php',
    'ExamTest\SampleTest'                => __DIR__ . '/tests/Exam/SampleTest.php',
);
