<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'view/user/account/denied' => __DIR__ . '/view/user/account/denied.phtml',
    'view/user/account/me'     => __DIR__ . '/view/user/account/me.phtml',
    'view/user/account/add'    => __DIR__ . '/view/user/account/add.phtml',
    'view/user/log/in'         => __DIR__ . '/view/user/log/in.phtml',
);
