<h1>Top Line</h1>
<?= $this->content ?>

<h1>Bottom Line</h1>
<?php
if ($this->profiler) {
    echo '<div id="profiler">Db Profiler:<br>';
	foreach($this->profiler->getProfiles() as $profile) {
		echo '"'. $profile['sql'].
			 ' ('.implode(',',$profile['parameters']->getNamedArray()).')" took '.
             $profile['elapse'].' seconds<br>';
	}
	echo '</div>';
}

echo '<div id="cache">Cache Hits:';
foreach($this->cache->hits as $key=>$count) {
	echo "$key => $count<br>\n";
}
echo '</div>';
?>
